[Service]
Host = "localhost"
Port = 49990
ConnectRetries = 3
HealthCheck = "/api/v1/ping"
Labels = []
OpenMsg = "device simple started"
ReadMaxLimit = 256
Timeout = 5000

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  name = "edgex-core-data"
  Host = "localhost"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  name = "edgex-core-metadata"
  Host = "localhost"
  Port = 48081
  Timeout = 50000

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
RemoteURL = ''
File = "./device-simple.log"

# Pre-define Schedule Configuration
[[schedules]]
name = "10sec-schedule"
frequency = "PT10S"

[[scheduleEvents]]
name = "readTemperature"
schedule = "10sec-schedule"
  [scheduleEvents.Addressable]
  method = "GET"
  path = "/api/v1/device/{name=JC.RR5.NAE9.ConfRoom.Padre.Island}/temperature"

[[scheduleEvents]]
name = "readHumidity"
schedule = "10sec-schedule"
  [scheduleEvents.Addressable]
  method = "GET"
  path = "/api/v1/device/{name=JC.RR5.NAE9.ConfRoom.Padre.Island}/humidity"

# trigger schedule by support-scheduler
[[scheduleEvents]]
name = "readTemperature"
schedule = "10sec-schedule"
service="edgex-support-scheduler"
  [scheduleEvents.Addressable]
  protocol = "HTTP"
  method = "GET"
  address = "edgex-device-simple"
  port = 49991
  path = "/api/v1/device/{name=JC.RR5.NAE9.ConfRoom.Padre.Island}/temperature"

[[schedules]]
name = "5sec-schedule"
frequency = "PT5S"

[[scheduleEvents]]
name = "readVoltage"
schedule = "5sec-schedule"
  [scheduleEvents.Addressable]
  method = "GET"
  path = "/api/v1/device/{name=GS1-AC-Drive}/voltage"
